dataset:
  img_suffix: .jpg
  kind: default
  pad_out_to_modulo: 8
device: cuda
fps: 25
indir: /media/mlpc2/workspace/sagor/TestingModels/lama/testImages
model:
  checkpoint: best.ckpt
  path: /media/mlpc2/workspace/sagor/TestingModels/lama/big-lama
out_ext: .jpg
out_key: inpainted
outdir: /media/mlpc2/workspace/sagor/TestingModels/lama/output
refine: true
refiner:
  gpu_ids: 0,
  lr: 0.002
  max_scales: 3
  min_side: 512
  modulo: ${dataset.pad_out_to_modulo}
  n_iters: 15
  px_budget: 900000
